### ISSUE TITLE
Having a hard time understanding use of pull-window recent in write

### ISSUE THREAD

**Issue by jtremback** [pull-stream/pull-level#2]
Hi, I noticed that `write` is using `pull-window` `.recent`. However, the documentation does not mention it, and I have always used it without `opts.windowSize, opts.windowTime`. I'm wondering what the effect of this is. I checked the `pull-window` tests, but I'm not seeing any examples of `recent` being used without arguments.

**Comment by regular** [comment]
Maybe things have changed since you had this conversation, but from looking at [the code](https://github.com/dominictarr/pull-window/blob/master/index.js#L76) it looks like, if `time` and `size` are both undefined/null, the only code path that calls done() is when the source stream ends. This would mean, per default the writestream buffers everything? I am sure I must be missing something ...

**Comment by dominictarr** [comment]
yeah that looks right, yeah it will still trigger the put once the stream ends (pretty sure).
looking at this I am surprised I didn't use a default setting for the time and window size in pull-level.
